### ISSUE TITLE
content directory is not automatically created

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#154]
## Description of issue
When running the GRA through the dotnet command line tool the following exception is thrown:

`Unhandled Exception: System.ArgumentException: The directory name /Users/user/repos/provo/gra4/src/GRA.Web/content/ is invalid.`

This occurs because the content folder is never created. To fix this I had to manually create a content folder.

## Notes

At the top of the "startup.cs" the ContentDirectory key is commented out. Instead it appears the ContentPath is being used, but perhaps they are two separate thing.

```
//{ ConfigurationKey.ContentDirectory, @"c:\inetpub\content\" },
{ ConfigurationKey.ContentPath, "content" }
```

Starting on line 57 or so there is code setup to create the ContentDirectory if it does not exist, but because the ContentPath is used instead, this code is never called.

## Additional Information
I am on Mac using the SQL Lite database provider.

**Comment by k7hpn** [comment]
I believe that:

- ContentDirectory is the path on disk to reach the content files
- ContentPath is the URL mapping to that directory (e.g. the `content` in `http://gra/content/`)

If `ContentDirectory` isn't set in the configuration then [this logic](https://github.com/MCLD/gra4/blob/a4d36c00dfde3ac49222ad8f902d78b856775846/src/GRA.Domain.Service/BadgeService.cs#L25-L35) seems to do the job which basically uses the `ContentPath` as the directory (i.e. a local directory under the project directory rather than a fully-qualifed path).

It looks like maybe the `startup.cs` logic should be altered to follow the same logic as above in `BadgeService.cs` or maybe we should abstract that logic out somewhere.

**Comment by k7hpn** [comment]
I think we've fixed this. Please reopen if there are further issues!
