### ISSUE TITLE
Events feature request

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#155]
**Description**
In GRA3 there was an events feature which allowed programs to add calendar events which were viewable by date, sortable by program, etc.

 I noticed that there is a small amount of code related to this in the GRA.Models section. Is this still a planned feature?

**Comment by k7hpn** [comment]
We are currently working on implementing events similarly to how they worked in 3.

One difference is that secret codes will be bound to triggers rather than events. Current work towards this effort is in my [triggers branch](https://github.com/haraldnagel/gra4/tree/triggers) and @iafb's [events branch](https://github.com/iafb/gra4/tree/Events).
