### ISSUE TITLE
Using HTML for challenge descriptions

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#156]
The current challenge descriptions are plain text, or are being auto escaped. It would be helpful if this field accepted HTML, for simple markup such as links and bullet points. I don't think it needs a full HTML editor in Mission Control to make this useful, but it might be a direction to go.

If you think this is a good idea I would be happy to work on it.

**Comment by k7hpn** [comment]
So in lieu of using HTML we were trying the approach of using Markdown in GRA 4. You can see the Markdown editor we're using in the "Pages" section of the software (though it needs a little more work, e.g. maybe tabbed preview rather than text on top and preview on bottom). The upshot of using Markdown is that HTML can be included in Markdown without any sort of escaping or qualification.

I was kind-of hoping to keep the descriptions of things like challenges as text so that on the details page they'd all be formatted the same but maybe it makes sense to use Markdown for those. It should be trivial to use the same Markdown editor for Challenge descriptions as we use for Pages.

@iafb - was there any reason we didn't use HTML in Challenge descriptions that you can think of?

**Comment by iafb** [comment]
I don't think there was any reason discussed for not doing it that way. If we do add HTML/Markdown to Challenge descriptions it'd probably make sense to use it for Events as well.

**Comment by k7hpn** [comment]
Agree with @iafb - we can do Markdown for Challenge and Event descriptions using the built-in Markdown editor. We may need to expand description fields to accept more text for this. If possible we should improve the Markdown editor and ensure it's pluggable so that as we improve it those improvements are reflected everywhere that it's used.

**Comment by justinmeiners** [comment]
Thanks for the replies to all my questions. I am a big fan of Markdown so It sounds like what you are proposing would work perfect.

**Comment by k7hpn** [comment]
This issue was resolved in #452 Add Challenge improvements
