### ISSUE TITLE
File not found error when inserting default avatars

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/gra4#312]
`"FileNotFoundException: Could not find file '/Users/(....)/gra4/src/GRA.Web/assets/dynamicavatars/default avatars.json'."`

This file does not appear to exist, despite being synced with the repo. Do these files need to be checked in?

**Comment by k7hpn** [comment]
We've not included the avatar image files in Git because it's a big blob of binary data and it seems like a pain to have that in the repository. We'll get a ZIP file uploaded somewhere with the default avatar set that you can copy into the `assets` directory so you can do the default avatar install.

**Comment by k7hpn** [comment]
Here's a file with a set of all of the default avatars:

[dynamicavatars.7z](http://greatreadingadventure.com/v4/dynamicavatars.7z) (41 MB)

You can follow these steps:

1. Download that file.
2. Unzip it to `src/GRA.Web/assets/`.
3. Go to the Flight Controller and click "Default Dynamic Avatars".
4. Wait. Running locally it may take > 2 minutes which may cause the Web request to timeout but never fear! The `async` method is still running in the background and will finish eventually.
5. Bask in the glory of the "RideBurgerCar" coat and the "GlitchamaphoneChickenMask" hat!
